version: 0.2

env:
  variables:
    AWS_REGION: "ap-southeast-1"
    AWS_ACCOUNT_ID: "654654447255"
    BACKEND_REPO_NAME: "web-backend"
    FRONTEND_REPO_NAME: "web-frontend"

phases:
  install:
    runtime-versions:
      docker: 20
    commands:
      - echo "Installing dependencies and preparing the environment..."
      - printenv
      # Nếu cần thiết, bạn có thể bỏ comment các lệnh sau để khởi động Docker daemon
      # - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 &
      # - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws --version
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - echo "Setting repository URIs..."
      - BACKEND_REPO_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$BACKEND_REPO_NAME
      - FRONTEND_REPO_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$FRONTEND_REPO_NAME
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - BACKEND_IMAGE_TAG=${COMMIT_HASH:-latest}
      - FRONTEND_IMAGE_TAG=${COMMIT_HASH:-latest}
      - echo "Listing root directory:"
      - ls -la

  build:
    commands:
      - echo "Build started on $(date)"

      # Xây dựng Docker image cho Backend
      - echo "Building the backend Docker image..."
      - docker build -t $BACKEND_REPO_NAME:latest --target backend -f Dockerfile .
      - docker tag $BACKEND_REPO_NAME:latest $BACKEND_REPO_URI:latest
      - docker tag $BACKEND_REPO_NAME:latest $BACKEND_REPO_URI:$BACKEND_IMAGE_TAG

      # Xây dựng Docker image cho Frontend
      - echo "Building the frontend Docker image..."
      - docker build -t $FRONTEND_REPO_NAME:latest --target frontend -f Dockerfile .
      - docker tag $FRONTEND_REPO_NAME:latest $FRONTEND_REPO_URI:latest
      - docker tag $FRONTEND_REPO_NAME:latest $FRONTEND_REPO_URI:$FRONTEND_IMAGE_TAG

      # Kiểm tra các image đã được build thành công
      - echo "Listing Docker images:"
      - docker images

  post_build:
    commands:
      - echo "Build completed on $(date)"

      # Đẩy Docker image của Backend lên ECR
      - echo "Pushing the backend Docker image to ECR..."
      - docker push $BACKEND_REPO_URI:latest
      - docker push $BACKEND_REPO_URI:$BACKEND_IMAGE_TAG

      # Đẩy Docker image của Frontend lên ECR
      - echo "Pushing the frontend Docker image to ECR..."
      - docker push $FRONTEND_REPO_URI:latest
      - docker push $FRONTEND_REPO_URI:$FRONTEND_IMAGE_TAG

      # Tạo file imagedefinitions.json cho ECS (nếu bạn sử dụng ECS)
      - echo "Writing image definitions file..."
      - printf '[{"name":"web-backend","imageUri":"%s"},{"name":"web-frontend","imageUri":"%s"}]' $BACKEND_REPO_URI:$BACKEND_IMAGE_TAG $FRONTEND_REPO_URI:$FRONTEND_IMAGE_TAG > imagedefinitions.json
      - ls -la

artifacts:
  files:
    - imagedefinitions.json
