version: 0.2

phases:
  install:
    commands:
      - echo "Khởi động Docker daemon..."
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 &
      - timeout 15 sh -c "until docker info; do echo 'Đang chờ Docker daemon...'; sleep 1; done"
      - echo "Docker daemon đã được khởi động."

  pre_build:
    commands:
      - echo "Đăng nhập vào Amazon ECR..."
      - aws --version
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 654654447255.dkr.ecr.ap-southeast-1.amazonaws.com
      - echo "Setting repository URIs..."
      - export BACKEND_REPO_URI=654654447255.dkr.ecr.ap-southeast-1.amazonaws.com/my-app-backend
      - export FRONTEND_REPO_URI=654654447255.dkr.ecr.ap-southeast-1.amazonaws.com/my-app-frontend
      - export COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - export IMAGE_TAG=${COMMIT_HASH:-latest}

  build:
    commands:
      # Build và tag Backend
      - echo "Build Docker image backend với tag latest..."
      - docker build -t $BACKEND_REPO_URI:latest ./web-backend
      - echo "Tag Docker image backend với tag commit hash..."
      - docker tag $BACKEND_REPO_URI:latest $BACKEND_REPO_URI:$IMAGE_TAG
      - echo "Docker images backend đã được build và tag thành công."

      # Build và tag Frontend
      - echo "Build Docker image frontend với tag latest..."
      - docker build -t $FRONTEND_REPO_URI:latest ./web-frontend
      - echo "Tag Docker image frontend với tag commit hash..."
      - docker tag $FRONTEND_REPO_URI:latest $FRONTEND_REPO_URI:$IMAGE_TAG
      - echo "Docker images frontend đã được build và tag thành công."

  post_build:
    commands:
      - echo "Build completed on $(date)"
      # Push Backend Images
      - echo "Pushing the backend Docker image to ECR..."
      - docker push $BACKEND_REPO_URI:latest
      - docker push $BACKEND_REPO_URI:$IMAGE_TAG
      # Push Frontend Images
      - echo "Pushing the frontend Docker image to ECR..."
      - docker push $FRONTEND_REPO_URI:latest
      - docker push $FRONTEND_REPO_URI:$IMAGE_TAG
      # Tạo file imagedefinitions.json
      - echo "Ghi file imagedefinitions.json..."
      - printf '[{"name":"my-app-backend","imageUri":"%s"},{"name":"my-app-frontend","imageUri":"%s"}]' $BACKEND_REPO_URI:$IMAGE_TAG $FRONTEND_REPO_URI:$IMAGE_TAG > imagedefinitions.json
      - echo "create imagedefinitions.json file"
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
