version: 0.2

phases:
  install:
    commands:
      - echo "Khởi động Docker daemon..."
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 &
      - timeout 15 sh -c "until docker info; do echo 'Đang chờ Docker daemon...'; sleep 1; done"
      - echo "Docker daemon đã được khởi động."

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws --version
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 654654447255.dkr.ecr.ap-southeast-1.amazonaws.com
      - echo "Setting repository URIs..."
      - BACKEND_REPO_URI=654654447255.dkr.ecr.ap-southeast-1.amazonaws.com/app-backend
      - FRONTEND_REPO_URI=654654447255.dkr.ecr.ap-southeast-1.amazonaws.com/app-frontend
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - BACKEND_IMAGE_TAG=${COMMIT_HASH:-latest}
      - FRONTEND_IMAGE_TAG=${COMMIT_HASH:-latest}

  build:
    commands:
      - echo "Build Docker image với tag latest..."
      - docker build -t $BACKEND_REPO_URI:latest .
      - echo "Tag Docker image với tag commit hash..."
      - docker tag $BACKEND_REPO_URI:latest $BACKEND_REPO_URI:$IMAGE_TAG
      - echo "Docker images đã được build và tag thành công."

      - echo "Tiến hành build Docker image..."
      - docker build -t $FRONTEND_REPO_URI:latest .
      - docker tag $FRONTEND_REPO_URI:latest $FRONTEND_REPO_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo "Build completed on $(date)"
      - echo "Pushing the backend Docker image to ECR..."
      - docker push $BACKEND_REPO_URI:latest
      - docker push $BACKEND_REPO_URI:$BACKEND_IMAGE_TAG
      - echo "Pushing the frontend Docker image to ECR..."
      - docker push $FRONTEND_REPO_URI:latest
      - docker push $FRONTEND_REPO_URI:$FRONTEND_IMAGE_TAG
      - echo "Writing image definitions file..."
      - printf '[{"name":"web-backend","imageUri":"%s"},{"name":"web-frontend","imageUri":"%s"}]' $BACKEND_REPO_URI:$BACKEND_IMAGE_TAG $FRONTEND_REPO_URI:$FRONTEND_IMAGE_TAG > imagedefinitions.json
      - echo "create imagedefinitions.json file"
artifacts:
  files:
    - imagedefinitions.json
