version: 0.2

phases:
  pre_build:
    commands:
      - echo "Đăng nhập vào Amazon ECR..."
      - aws --version
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 654654447255.dkr.ecr.ap-southeast-1.amazonaws.com
      - echo "Setting repository URIs..."
      - export BACKEND_REPO_URI=654654447255.dkr.ecr.ap-southeast-1.amazonaws.com/my-app-backend
      - export FRONTEND_REPO_URI=654654447255.dkr.ecr.ap-southeast-1.amazonaws.com/my-app-frontend
      - export COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - export IMAGE_TAG=${COMMIT_HASH:-latest}

  build:
    commands:
      - echo "Build Docker image backend với tag latest..."
      - docker build --platform linux/amd64 -t $BACKEND_REPO_URI:latest ./web-backend
      - echo "Tag Docker image backend với tag commit hash..."
      - docker tag $BACKEND_REPO_URI:latest $BACKEND_REPO_URI:$IMAGE_TAG

      - echo "Build Docker image frontend với tag latest..."
      - docker build --platform linux/amd64 -t $FRONTEND_REPO_URI:latest ./web-frontend
      - echo "Tag Docker image frontend với tag commit hash..."
      - docker tag $FRONTEND_REPO_URI:latest $FRONTEND_REPO_URI:$IMAGE_TAG

      # Kiểm Tra Nội Dung Docker Images
      - echo "Kiểm tra nội dung Docker image backend..."
      - docker run --rm $BACKEND_REPO_URI:latest ls -la /app
      - echo "Kiểm tra nội dung Docker image frontend..."
      - docker run --rm $FRONTEND_REPO_URI:latest ls -la /app

  post_build:
    commands:
      - echo "Build completed on $(date)"

      - echo "Pushing the backend Docker image to ECR..."
      - docker push $BACKEND_REPO_URI:latest
      - docker push $BACKEND_REPO_URI:$IMAGE_TAG

      - echo "Pushing the frontend Docker image to ECR..."
      - docker push $FRONTEND_REPO_URI:latest
      - docker push $FRONTEND_REPO_URI:$IMAGE_TAG

      - echo "Ghi file imagedefinitions.json..."
      - printf '[{"name":"my-app-backend","imageUri":"%s"},{"name":"my-app-frontend","imageUri":"%s"}]' $BACKEND_REPO_URI:$IMAGE_TAG $FRONTEND_REPO_URI:$IMAGE_TAG > imagedefinitions.json
      - echo "create imagedefinitions.json file"
      - cat imagedefinitions.json

artifacts:
  files:
    - appspec.yml
    - scripts/**
    - docker-compose.yml
    - imagedefinitions.json
    - web-backend/**
    - web-frontend/**
