version: "3.9"
services:
  backend:
    build:
      context: ./web-backend
      dockerfile: Dockerfile
    container_name: backend
    expose:
      - "5000"
    env_file:
      - ./web-backend/.env

  frontend:
    build:
      context: ./web-frontend
      dockerfile: Dockerfile
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    env_file:
      - ./web-frontend/.env
