version: "3.9"
services:
  backend:
    build:
      context: ./web-backend
      dockerfile: Dockerfile
    container_name: backend
    # Không cần volumes
    ports:
      - "5000:5000"
    env_file:
      - ./web-backend/.env

  frontend:
    build:
      context: ./web-frontend
      dockerfile: Dockerfile
    container_name: frontend
    # Không cần volumes
    ports:
      - "80:80" # Nếu bạn dùng nginx để serve static frontend
    depends_on:
      - backend
    env_file:
      - ./web-frontend/.env
