version: "3.8"

services:
  web-backend:
    build:
      context: ./web-backend
      dockerfile: Dockerfile
    restart: always
    networks:
      - web-network

  web-frontend:
    build:
      context: ./web-frontend
      dockerfile: Dockerfile
    restart: always
    networks:
      - web-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always
    depends_on:
      - web-frontend
      - web-backend
    networks:
      - web-network

networks:
  web-network:
    driver: bridge
