version: "3.9"
services:
  backend:
    build:
      context: ./web-backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./web-backend/.env

  frontend:
    build:
      context: ./web-frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    env_file:
      - ./web-frontend/.env
    depends_on:
      - backend
