version: "3"
services:
  backend:
    image: 654654447255.dkr.ecr.ap-southeast-1.amazonaws.com/my-app-backend:latest
    ports:
      - "5000:5000"
    restart: always
  frontend:
    image: 654654447255.dkr.ecr.ap-southeast-1.amazonaws.com/my-app-frontend:latest
    ports:
      - "5173:5173"
    restart: always
